<?php
  $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
  $customerSession = $objectManager->get('Magento\Customer\Model\Session');
  $status = $customerSession->getCustomer()->getCustomerStatus(); // get ID
?>

<fieldset class="fieldset edit account" >
  <div class="field customer_status ">
    <label for="customer_status" class="label"><span><?php /* @escapeNotVerified */ echo __('Status') ?></span></label>
    <div class="control">
        <input value="<?php echo $status?>" type="text" name="customer_status" id="customer_status" title="<?php /* @escapeNotVerified */ echo __('Status') ?>" class="input-text" autocomplete="off">
    </div>
  </div>
</fieldset>
